import type { CatalogService, CatalogVenue } from "./catalog";

export const fallbackServices: CatalogService[] = [
  {
    id: "booth-reservation",
    label: "Booth Reservation",
    packages: [
      { label: "Compact Size 6' x 6' ft (36 sq ft)", href: "/packages/booth-reservation/compact" },
      { label: "Standard Size 6' x 9' ft (54 sq ft)", href: "/packages/booth-reservation/standard" },
      { label: "Premium Size 10' x 10' ft (100 sq ft)", href: "/packages/booth-reservation/premium" },
      { label: "Executive 16' x 20' ft (380 sq ft)", href: "/packages/booth-reservation/executive" },
      { label: "Custom Size", href: "/packages/booth-reservation/custom" },
    ],
  },
  {
    id: "booth-design",
    label: "Booth Design",
    packages: [
      { label: "Essential Design", href: "/packages/booth-design/essential" },
      { label: "Professional Design", href: "/packages/booth-design/professional" },
      { label: "Premium Design", href: "/packages/booth-design/premium" },
      { label: "Luxury Design", href: "/packages/booth-design/luxury" },
      { label: "Custom Design", href: "/packages/booth-design/custom" },
    ],
  },
  {
    id: "booth-install-demolition",
    label: "Booth Install & Demolition",
    packages: [
      { label: "Basic Installation", href: "/packages/booth-install-demolition/basic" },
      { label: "Standard Installation", href: "/packages/booth-install-demolition/standard" },
      { label: "Premium Installation", href: "/packages/booth-install-demolition/premium" },
      { label: "Deluxe Installation", href: "/packages/booth-install-demolition/deluxe" },
    ],
  },
  {
    id: "logistics",
    label: "Logistics Services",
    packages: [
      { label: "Basic Logistics Package", href: "/packages/logistics/basic" },
      { label: "Standard Logistics Package", href: "/packages/logistics/standard" },
      { label: "Premium Logistics Package", href: "/packages/logistics/premium" },
      { label: "Full Freight Management", href: "/packages/logistics/freight" },
    ],
  },
  {
    id: "marketing",
    label: "Marketing Services",
    packages: [
      { label: "Basic Marketing Package", href: "/packages/marketing/basic" },
      { label: "Digital Marketing Package", href: "/packages/marketing/digital" },
      { label: "Premium Marketing Package", href: "/packages/marketing/premium" },
      { label: "Full Marketing Campaign", href: "/packages/marketing/campaign" },
    ],
  },
  {
    id: "interpretation-protocol",
    label: "Interpretation & Protocol Services",
    packages: [
      { label: "Basic Interpretation", href: "/packages/interpretation-protocol/basic" },
      { label: "Professional Interpretation", href: "/packages/interpretation-protocol/professional" },
      { label: "VIP Protocol Services", href: "/packages/interpretation-protocol/vip" },
      { label: "Full Protocol Management", href: "/packages/interpretation-protocol/management" },
    ],
  },
  {
    id: "manpower",
    label: "Apply for Man Power Service",
    packages: [{ label: "Individual Application", href: "/manpower" }],
  },
];

export const fallbackVenues: CatalogVenue[] = [
  {
    id: 1,
    locationId: "yashobhoomi",
    subVenueId: "iicc-dwarka",
    name: "Yashobhoomi, India International Convention and Expo Centre",
    address: "Sector 25, Dwarka, New Delhi - 110061",
    city: "New Delhi",
    state: "Delhi",
    description: "Priority HOI service venue for exhibition support, booth services, logistics, marketing, interpretation, and manpower.",
    about: "Yashobhoomi is the primary HOI service location in Dwarka, New Delhi.",
    totalArea: "India's largest MICE destination",
    halls: "Exhibition and convention halls",
    capacity: "Large-scale exhibitions and business events",
    established: "2023",
    website: "https://www.yashobhoomi.org/",
    specialities: ["Priority HOI Venue", "Exhibition Services", "Convention Centre", "Business Events"],
    image: "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&w=1600&q=80",
  },
  {
    id: 2,
    locationId: "delhi",
    subVenueId: "pragati-maidan",
    name: "Pragati Maidan (ITPO)",
    address: "Bhairon Marg, Pragati Maidan, New Delhi - 110001",
    city: "New Delhi",
    state: "Delhi",
    description: "India's iconic exhibition ground managed by ITPO.",
    about: "Pragati Maidan is a major trade exhibition venue in Delhi.",
    totalArea: "123 acres",
    halls: "14 Halls",
    capacity: "50,000+ visitors/day",
    established: "1972",
    website: "",
    specialities: ["International Trade Fairs", "Government Pavilions", "ITPO Managed Events"],
    image: "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=80",
  },
  {
    id: 3,
    locationId: "mumbai",
    subVenueId: "bombay-exhibition-centre",
    name: "Bombay Exhibition Centre",
    address: "Western Express Highway, Goregaon East, Mumbai - 400063",
    city: "Mumbai",
    state: "Maharashtra",
    description: "Mumbai's premier exhibition and convention center.",
    about: "Bombay Exhibition Centre hosts international trade shows and corporate events.",
    totalArea: "50,000 sq m",
    halls: "8 Halls",
    capacity: "25,000+ visitors",
    established: "1978",
    website: "",
    specialities: ["International Trade Shows", "Corporate Events", "Product Launches"],
    image: "https://images.unsplash.com/photo-1497366754035-f200968a6e72?w=800&q=80",
  },
];
