allowBuilds:
  '@firebase/util': set this to true or false
  esbuild: false
  protobufjs: set this to true or false
ignoredBuiltDependencies:
  - esbuild
strictDepBuilds: false
managePackageManagerVersions: false
verifyDepsBeforeRun: false
